services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: chronos-db
    ports:
      - 5433:5432
    restart: on-failure

  postgres-test:
    image: postgres:latest
    container_name: postgres-test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: chatX_test
    ports:
      - 5434:5432   
    restart: on-failure